package com.zombie.model.enumerations;

public enum PlayerEvent {
	ERROR_MINIMUM_PLAYERS_LIMIT,
	ERROR_MAXIMUM_PLAYERS_LIMIT,
	SHOW_LOADED_PLAYER_PANEL,
	ERROR_PLAYER_VALIDATION,
	SHOW_WAITING_PLAYERS_PANEL,
	GLOBAL_EVENT,
	ERROR_REMOTE_EXCEPTION
}
